### ISSUE TITLE
State design pattern

### ISSUE THREAD

**Issue by tonilopezmr** [CloudCoders/Design-Patterns#17]
https://sourcemaking.com/design_patterns/state 👍 🔥 🔥 🔥

**Comment by tonilopezmr** [comment]
Also Could be an interesting discussion about Strategy and State

**Comment by Cotel** [comment]
Dunno if they are compatible as we implemented them. Stategies are FP like because they are functions stored in constants. What's your idea? @tonilopezmr

**Comment by tonilopezmr** [comment]
I don't know yet
