### ISSUE TITLE
Add Maybe Monad

### ISSUE THREAD

**Issue by Cotel** [CloudCoders/Design-Patterns#26]
Remember all monads are funtors. Inspiration taken from [this series](https://elabismodenull.wordpress.com/2016/12/30/programacion-funcional-en-javascript-los-funtores/)

**Comment by Cotel** [comment]
This monad is also known as *Option*. Which is the name the gave to it in [katz](https://github.com/FineCinnamon/Katz/blob/master/katz/src/main/kotlin/katz/data/Option.kt)

**Comment by tonilopezmr** [comment]
Ahhh okey is an Option!
