### ISSUE TITLE
Write tests for Little Kai

### ISSUE THREAD

**Issue by Cotel** [CloudCoders/Design-Patterns#3]
How Decorators should be tested? Lets find out!

**Comment by tonilopezmr** [comment]
Very easy @Cotel give me an example of Little Kai Noddle elaboration

**Comment by tonilopezmr** [comment]
Okey I have found it! https://github.com/CloudCoders/Design-Patterns/blob/master/src/main/kotlin/Decorator/littlekai/Main.kt

Your `main` at the moment in your life it's your way to know if your program it's works or not. You should only represent your main in test.

Your packages `base` `noodles` `ingredients` `sauces` are your models, and `Main.tk` it's your program, what do you want to tests? Your models or your program?  (unit or aceptance)

You are interested in test your models.

**Comment by tonilopezmr** [comment]
Do you want to write a simple test to check that your model is good?

**Comment by Cotel** [comment]
I've implemented some tests. I don't know if they are doing a good coverage. (I don't really know how to tests these patterns) 😵

**Comment by tonilopezmr** [comment]
I'm going to see
